Deploy for release 0.5.0 from 21f3cc0a5f4e8db09afc0287a8b785ba4de6eb95

diff --git a/target/docker/integrate/harmonypy/harmonypy b/target/docker/integrate/harmonypy/harmonypy
--- a/target/docker/integrate/harmonypy/harmonypy
+++ b/target/docker/integrate/harmonypy/harmonypy
@@ -199,7 +199,7 @@ function ViashHelp {
   echo "        of theta result in more diverse clusters."
   echo ""
   echo "    --obs_covariates"
-  echo "        type: string, multiple values allowed"
+  echo "        type: string, required parameter, multiple values allowed"
   echo "        example: batch:sample"
   echo "        The .obs field(s) that define the covariate(s) to regress out."
 }
@@ -425,9 +425,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries Schaumont <dries.schaumont@its.jnj.com> (maintainer), Robrecht Cannoodt <rcannood@gmail.com> (contributor) {github: rcannood, orcid: 0000-0003-3641-729X}"
 LABEL org.opencontainers.image.description="Companion container for running component integrate harmonypy"
-LABEL org.opencontainers.image.created="2022-09-14T09:34:09Z"
+LABEL org.opencontainers.image.created="2022-09-15T21:00:46Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="431ea87c708ebea039c5b5594072184938ad6e2a"
+LABEL org.opencontainers.image.revision="21f3cc0a5f4e8db09afc0287a8b785ba4de6eb95"
 LABEL org.opencontainers.image.version="0.5.0"
 VIASHDOCKER
 }
@@ -804,6 +804,10 @@ if [ -z ${VIASH_PAR_INPUT+x} ]; then
 fi
 if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
   ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z ${VIASH_PAR_OBS_COVARIATES+x} ]; then
+  ViashError '--obs_covariates' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z ${VIASH_PAR_MODALITY+x} ]; then
