deploy: 57a19b82087425f8aa43e8741a9708572f9f6914

diff --git a/target/docker/qc/calculate_qc_metrics/calculate_qc_metrics b/target/docker/qc/calculate_qc_metrics/calculate_qc_metrics
--- a/target/docker/qc/calculate_qc_metrics/calculate_qc_metrics
+++ b/target/docker/qc/calculate_qc_metrics/calculate_qc_metrics
@@ -208,6 +208,7 @@ function ViashHelp {
   echo "        type: string"
   echo "        example: raw_counts"
   echo ""
+  echo "Metrics added to .obs:"
   echo "    --var_qc_metrics"
   echo "        type: string, multiple values allowed"
   echo "        example: ercc,highly_variable,mitochondrial"
@@ -229,6 +230,49 @@ function ViashHelp {
   echo "        If not specified, proportions are not calculated. \`--top_n_vars 20,50\`"
   echo "        finds"
   echo "        cumulative proportion to the 20th and 50th most expressed vars."
+  echo ""
+  echo "    --output_obs_num_nonzero_vars"
+  echo "        type: string"
+  echo "        default: num_nonzero_vars"
+  echo "        Name of column in .obs describing, for each observation, the number of"
+  echo "        stored values"
+  echo "        (including explicit zeroes). In other words, the name of the column that"
+  echo "        counts"
+  echo "        for each row the number of columns that contain data."
+  echo ""
+  echo "    --output_obs_total_counts_vars"
+  echo "        type: string"
+  echo "        default: total_counts"
+  echo "        Name of the column for .obs describing, for each observation (row),"
+  echo "        the sum of the stored values in the columns."
+  echo ""
+  echo "Metrics added to .var:"
+  echo "    --output_var_num_nonzero_obs"
+  echo "        type: string"
+  echo "        default: num_nonzero_obs"
+  echo "        Name of column describing, for each feature, the number of stored values"
+  echo "        (including explicit zeroes). In other words, the name of the column that"
+  echo "        counts"
+  echo "        for each column the number of rows that contain data."
+  echo ""
+  echo "    --output_var_total_counts_obs"
+  echo "        type: string"
+  echo "        default: total_counts"
+  echo "        Name of the column in .var describing, for each feature (column),"
+  echo "        the sum of the stored values in the rows."
+  echo ""
+  echo "    --output_var_obs_mean"
+  echo "        type: string"
+  echo "        default: obs_mean"
+  echo "        Name of the column in .obs providing the mean of the values in each row."
+  echo ""
+  echo "    --output_var_pct_dropout"
+  echo "        type: string"
+  echo "        default: pct_dropout"
+  echo "        Name of the column in .obs providing for each feature the percentage of"
+  echo "        observations the feature does not appear on (i.e. is missing). Same as"
+  echo "        \`--num_nonzero_obs\`"
+  echo "        but percentage based."
   echo ""
   echo "Outputs:"
   echo "    --output"
@@ -472,9 +516,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries Schaumont"
 LABEL org.opencontainers.image.description="Companion container for running component qc calculate_qc_metrics"
-LABEL org.opencontainers.image.created="2024-01-09T08:43:32Z"
+LABEL org.opencontainers.image.created="2024-01-12T08:26:06Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="1e947b7c3c163b2b9289775849c79848b1af3dbd"
+LABEL org.opencontainers.image.revision="de028d8b21b82c99fa574f706c66984faee5b2bb"
 LABEL org.opencontainers.image.version="main_build"
 
 VIASHDOCKER
@@ -707,6 +751,72 @@ while [[ $# -gt 0 ]]; do
             fi
             shift 1
             ;;
+        --output_obs_num_nonzero_vars)
+            [ -n "$VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS" ] && ViashError Bad arguments for option \'--output_obs_num_nonzero_vars\': \'$VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_obs_num_nonzero_vars. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_obs_num_nonzero_vars=*)
+            [ -n "$VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS" ] && ViashError Bad arguments for option \'--output_obs_num_nonzero_vars=*\': \'$VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_obs_total_counts_vars)
+            [ -n "$VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS" ] && ViashError Bad arguments for option \'--output_obs_total_counts_vars\': \'$VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_obs_total_counts_vars. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_obs_total_counts_vars=*)
+            [ -n "$VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS" ] && ViashError Bad arguments for option \'--output_obs_total_counts_vars=*\': \'$VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_var_num_nonzero_obs)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS" ] && ViashError Bad arguments for option \'--output_var_num_nonzero_obs\': \'$VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_var_num_nonzero_obs. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_var_num_nonzero_obs=*)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS" ] && ViashError Bad arguments for option \'--output_var_num_nonzero_obs=*\': \'$VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_var_total_counts_obs)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS" ] && ViashError Bad arguments for option \'--output_var_total_counts_obs\': \'$VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_var_total_counts_obs. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_var_total_counts_obs=*)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS" ] && ViashError Bad arguments for option \'--output_var_total_counts_obs=*\': \'$VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_var_obs_mean)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_OBS_MEAN" ] && ViashError Bad arguments for option \'--output_var_obs_mean\': \'$VIASH_PAR_OUTPUT_VAR_OBS_MEAN\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_OBS_MEAN="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_var_obs_mean. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_var_obs_mean=*)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_OBS_MEAN" ] && ViashError Bad arguments for option \'--output_var_obs_mean=*\': \'$VIASH_PAR_OUTPUT_VAR_OBS_MEAN\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_OBS_MEAN=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_var_pct_dropout)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT" ] && ViashError Bad arguments for option \'--output_var_pct_dropout\': \'$VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --output_var_pct_dropout. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --output_var_pct_dropout=*)
+            [ -n "$VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT" ] && ViashError Bad arguments for option \'--output_var_pct_dropout=*\': \'$VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output)
             [ -n "$VIASH_PAR_OUTPUT" ] && ViashError Bad arguments for option \'--output\': \'$VIASH_PAR_OUTPUT\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_OUTPUT="$2"
@@ -875,6 +985,24 @@ fi
 # filling in defaults
 if [ -z ${VIASH_PAR_MODALITY+x} ]; then
   VIASH_PAR_MODALITY="rna"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS+x} ]; then
+  VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS="num_nonzero_vars"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS+x} ]; then
+  VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS="total_counts"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS+x} ]; then
+  VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS="num_nonzero_obs"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS+x} ]; then
+  VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS="total_counts"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_VAR_OBS_MEAN+x} ]; then
+  VIASH_PAR_OUTPUT_VAR_OBS_MEAN="obs_mean"
+fi
+if [ -z ${VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT+x} ]; then
+  VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT="pct_dropout"
 fi
 
 # check whether required files exist
@@ -1047,6 +1175,12 @@ par = {
   'var_qc_metrics': $( if [ ! -z ${VIASH_PAR_VAR_QC_METRICS+x} ]; then echo "r'${VIASH_PAR_VAR_QC_METRICS//\'/\'\"\'\"r\'}'.split(',')"; else echo None; fi ),
   'var_qc_metrics_fill_na_value': $( if [ ! -z ${VIASH_PAR_VAR_QC_METRICS_FILL_NA_VALUE+x} ]; then echo "r'${VIASH_PAR_VAR_QC_METRICS_FILL_NA_VALUE//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'top_n_vars': $( if [ ! -z ${VIASH_PAR_TOP_N_VARS+x} ]; then echo "list(map(int, r'${VIASH_PAR_TOP_N_VARS//\'/\'\"\'\"r\'}'.split(',')))"; else echo None; fi ),
+  'output_obs_num_nonzero_vars': $( if [ ! -z ${VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS+x} ]; then echo "r'${VIASH_PAR_OUTPUT_OBS_NUM_NONZERO_VARS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_obs_total_counts_vars': $( if [ ! -z ${VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS+x} ]; then echo "r'${VIASH_PAR_OUTPUT_OBS_TOTAL_COUNTS_VARS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_var_num_nonzero_obs': $( if [ ! -z ${VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS+x} ]; then echo "r'${VIASH_PAR_OUTPUT_VAR_NUM_NONZERO_OBS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_var_total_counts_obs': $( if [ ! -z ${VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS+x} ]; then echo "r'${VIASH_PAR_OUTPUT_VAR_TOTAL_COUNTS_OBS//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_var_obs_mean': $( if [ ! -z ${VIASH_PAR_OUTPUT_VAR_OBS_MEAN+x} ]; then echo "r'${VIASH_PAR_OUTPUT_VAR_OBS_MEAN//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'output_var_pct_dropout': $( if [ ! -z ${VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT+x} ]; then echo "r'${VIASH_PAR_OUTPUT_VAR_PCT_DROPOUT//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'output': $( if [ ! -z ${VIASH_PAR_OUTPUT+x} ]; then echo "r'${VIASH_PAR_OUTPUT//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'output_compression': $( if [ ! -z ${VIASH_PAR_OUTPUT_COMPRESSION+x} ]; then echo "r'${VIASH_PAR_OUTPUT_COMPRESSION//\'/\'\"\'\"r\'}'"; else echo None; fi )
 }
@@ -1099,16 +1233,35 @@ def main():
     if isspmatrix_coo(layer):
         layer = csr_matrix(layer)
     layer.eliminate_zeros()
-    
+
+    var_columns_to_add = {}
+
     # var statistics
+    if par['output_var_obs_mean']:
+        obs_mean, _  = mean_variance_axis(layer, axis=0)
+        var_columns_to_add[par['output_var_obs_mean']] = obs_mean
+    if par['output_var_total_counts_obs']:
+        total_counts_obs = np.ravel(layer.sum(axis=0))
+        var_columns_to_add[par['output_var_total_counts_obs']] = total_counts_obs
+
     num_nonzero_obs = layer.getnnz(axis=0)
-    obs_mean, _  = mean_variance_axis(layer, axis=0)
-    pct_dropout = (1 - num_nonzero_obs / layer.shape[0]) * 100
-    total_counts_obs = np.ravel(layer.sum(axis=0))
+    if par['output_var_num_nonzero_obs']:
+       var_columns_to_add[par['output_var_num_nonzero_obs']] = num_nonzero_obs
+    if par['output_var_pct_dropout']:
+        var_columns_to_add[par['output_var_pct_dropout']] = (1 - num_nonzero_obs / layer.shape[0]) * 100
+
+    modality_data.var = modality_data.var.assign(**var_columns_to_add)
 
     # obs statistics
-    num_nonzero_vars = layer.getnnz(axis=1)
+    obs_columns_to_add = {}
     total_counts_var = np.ravel(layer.sum(axis=1))
+
+    if par['output_obs_num_nonzero_vars']:
+       num_nonzero_vars = layer.getnnz(axis=1)
+       obs_columns_to_add[par['output_obs_num_nonzero_vars']] = num_nonzero_vars
+
+    if par['output_obs_total_counts_vars']:
+        obs_columns_to_add[par['output_obs_total_counts_vars']] = total_counts_var
 
     top_metrics = {}
     if par["top_n_vars"]:
@@ -1117,13 +1270,14 @@ def main():
         top_metrics = {distribution_size: distribution * 100
                        for distribution_size, distribution 
                        in zip(par["top_n_vars"], distributions.T)}
+        obs_columns_to_add |= {f"pct_of_counts_in_top_{n_top}_vars": col for
+                               n_top, col in top_metrics.items()}
     
-    total_expr_qc = {}
-    pct_expr_qc = {}
     if par["var_qc_metrics"]:
+        print(f"qc_metrics: {par['var_qc_metrics']}")
         for qc_metric in par["var_qc_metrics"]:
             if not qc_metric in var:
-                raise ValueError(f"Value for --var_qc_metrics, {qc_metric} "
+                raise ValueError(f"Value for --var_qc_metrics, '{qc_metric}' "
                                  f"not found in .var for modality {par['modality']}")
             qc_column = var[qc_metric]
             if qc_column.isna().any():
@@ -1137,23 +1291,13 @@ def main():
             if set(np.unique(qc_column)) - {True, False}:
                 raise ValueError(f"Column {qc_metric} in .var for modality {par['modality']} "
                                  f"must only contain boolean values")
-            
-            total_expr_qc[qc_metric] = np.ravel(layer[:, qc_column].sum(axis=1))
-            pct_expr_qc[qc_metric] =  total_expr_qc[qc_metric] / total_counts_var * 100
-    
-    # Write all of the calculated statistics
-    modality_data.var = modality_data.var.assign(
-        **{"pct_dropout": pct_dropout,
-           "num_nonzero_obs": num_nonzero_obs,
-           "obs_mean": obs_mean,
-           "total_counts": total_counts_obs})
-    
-    modality_data.obs = modality_data.obs.assign(
-        **({"num_nonzero_vars": num_nonzero_vars,
-            "total_counts": total_counts_var} | \\
-           {f"pct_{qc_metric}": col for qc_metric, col in pct_expr_qc.items()} | \\
-           {f"total_counts_{qc_metrix}": col for qc_metrix, col in total_expr_qc.items()}) | \\
-           {f"pct_of_counts_in_top_{n_top}_vars": col for n_top, col in top_metrics.items()})
+            total_counts_qc_metric = np.ravel(layer[:, qc_column].sum(axis=1))
+            obs_columns_to_add |= {
+                f"total_counts_{qc_metric}": total_counts_qc_metric,
+                f"pct_{qc_metric}": total_counts_qc_metric / total_counts_var * 100
+            }
+
+    modality_data.obs = modality_data.obs.assign(**obs_columns_to_add)
 
     input_data.write(par["output"], compression=par["output_compression"])
             
