deploy: afcb33f0cf2748b0c8b6f5eba5a864d7844e9470

diff --git a/target/docker/neighbors/bbknn/bbknn b/target/docker/neighbors/bbknn/bbknn
--- a/target/docker/neighbors/bbknn/bbknn
+++ b/target/docker/neighbors/bbknn/bbknn
@@ -165,7 +165,7 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    -i, --input"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        Input h5mu file"
   echo ""
   echo "    --modality"
@@ -462,9 +462,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries De Maeyer, Dries Schaumont"
 LABEL org.opencontainers.image.description="Companion container for running component neighbors bbknn"
-LABEL org.opencontainers.image.created="2023-08-23T13:15:39Z"
+LABEL org.opencontainers.image.created="2023-08-24T11:05:40Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="7b1416e9022c9b39aa861271b7a4f3e67b78d8cf"
+LABEL org.opencontainers.image.revision="afcb33f0cf2748b0c8b6f5eba5a864d7844e9470"
 LABEL org.opencontainers.image.version="integration_build"
 
 VIASHDOCKER
@@ -881,6 +881,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT+x} ]; then
+  ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
   ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
