deploy: 493a3b7a14c3d347c8e770edba4a3682323ec9f0

diff --git a/target/docker/neighbors/bbknn/bbknn b/target/docker/neighbors/bbknn/bbknn
--- a/target/docker/neighbors/bbknn/bbknn
+++ b/target/docker/neighbors/bbknn/bbknn
@@ -165,7 +165,7 @@ function ViashHelp {
   echo ""
   echo "Arguments:"
   echo "    -i, --input"
-  echo "        type: file, file must exist"
+  echo "        type: file, required parameter, file must exist"
   echo "        Input h5mu file"
   echo ""
   echo "    --modality"
@@ -462,9 +462,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries De Maeyer, Dries Schaumont"
 LABEL org.opencontainers.image.description="Companion container for running component neighbors bbknn"
-LABEL org.opencontainers.image.created="2023-08-23T12:13:02Z"
+LABEL org.opencontainers.image.created="2023-08-24T08:32:35Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="5e9431504b8f53e9d069fb3a8fd35f82e44be05f"
+LABEL org.opencontainers.image.revision="493a3b7a14c3d347c8e770edba4a3682323ec9f0"
 LABEL org.opencontainers.image.version="main_build"
 
 VIASHDOCKER
@@ -881,6 +881,10 @@ fi
 
 
 # check whether required parameters exist
+if [ -z ${VIASH_PAR_INPUT+x} ]; then
+  ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
   ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
