deploy: d6de094d0182b1dd7d4c4ff1773a4ef965c58453

diff --git a/target/docker/mapping/cellranger_count/cellranger_count b/target/docker/mapping/cellranger_count/cellranger_count
--- a/target/docker/mapping/cellranger_count/cellranger_count
+++ b/target/docker/mapping/cellranger_count/cellranger_count
@@ -214,7 +214,7 @@ function ViashHelp {
   echo "        type: string"
   echo "        default: auto"
   echo "        choices: [ auto, threeprime, fiveprime, SC3Pv1, SC3Pv2, SC3Pv3, SC3Pv4,"
-  echo "SC3Pv3LT, SC3Pv3HT, SC5P-PE, SC5P-R2, SC-FB, ARC-v1 ]"
+  echo "SC3Pv3LT, SC3Pv3HT, SC5P-PE-v3, SC5P-PE, SC5P-R2, SC-FB, ARC-v1 ]"
   echo "        Assay configuration."
   echo "        - auto: autodetect mode"
   echo "        - threeprime: Single Cell 3'"
@@ -227,6 +227,7 @@ function ViashHelp {
   echo "        - SC3Pv4: Single Cell 3' v4"
   echo "        - SC3Pv3LT: Single Cell 3' v3 LT"
   echo "        - SC3Pv3HT: Single Cell 3' v3 HT"
+  echo "        - SC5P-PE-v3: Single Cell 5' paired-end v3 (GEM-X)"
   echo "        - SC5P-PE: Single Cell 5' paired-end"
   echo "        - SC5P-R2: Single Cell 5' R2-only"
   echo "        - SC-FB: Single Cell Antibody-only 3' v2 or 5'"
@@ -270,6 +271,17 @@ function ViashHelp {
   echo "        type: boolean"
   echo "        default: true"
   echo "        Whether to check for barcode compatibility between libraries."
+  echo ""
+  echo "    --min_crispr_umi"
+  echo "        type: integer"
+  echo "        min: 1"
+  echo "        Set the minimum number of CRISPR guide RNA UMIs required for protospacer"
+  echo "        detection."
+  echo "        If a lower or higher sensitivity is desired for detection, this value"
+  echo "        can be customized"
+  echo "        according to specific experimental needs. Applicable only to datasets"
+  echo "        that include a"
+  echo "        CRISPR Guide Capture library."
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -497,9 +509,9 @@ apt upgrade -y && apt install -y procps && rm -rf /var/lib/apt/lists/*
 
 LABEL org.opencontainers.image.authors="Angela Oliveira Pisco, Samuel D'Souza, Robrecht Cannoodt"
 LABEL org.opencontainers.image.description="Companion container for running component mapping cellranger_count"
-LABEL org.opencontainers.image.created="2024-06-13T02:41:33Z"
+LABEL org.opencontainers.image.created="2024-06-14T02:41:55Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="6b7dceade42a9fd30076c90b3cd0af10b46da8e8"
+LABEL org.opencontainers.image.revision="00610b1434fd34a8205c9ba31204a3a9584015f3"
 LABEL org.opencontainers.image.version="integration_build"
 
 VIASHDOCKER
@@ -809,6 +821,17 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_LIBRARY_COMPATIBILITY_CHECK=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --min_crispr_umi)
+            [ -n "$VIASH_PAR_MIN_CRISPR_UMI" ] && ViashError Bad arguments for option \'--min_crispr_umi\': \'$VIASH_PAR_MIN_CRISPR_UMI\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_MIN_CRISPR_UMI="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --min_crispr_umi. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --min_crispr_umi=*)
+            [ -n "$VIASH_PAR_MIN_CRISPR_UMI" ] && ViashError Bad arguments for option \'--min_crispr_umi=*\': \'$VIASH_PAR_MIN_CRISPR_UMI\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_MIN_CRISPR_UMI=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         ---setup)
             VIASH_MODE='docker_setup'
             VIASH_DOCKER_SETUP_STRATEGY="$2"
@@ -1057,6 +1080,16 @@ if [[ -n "$VIASH_PAR_LIBRARY_COMPATIBILITY_CHECK" ]]; then
     exit 1
   fi
 fi
+if [[ -n "$VIASH_PAR_MIN_CRISPR_UMI" ]]; then
+  if ! [[ "$VIASH_PAR_MIN_CRISPR_UMI" =~ ^[-+]?[0-9]+$ ]]; then
+    ViashError '--min_crispr_umi' has to be an integer. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+  if [[ $VIASH_PAR_MIN_CRISPR_UMI -lt 1 ]]; then
+    ViashError '--min_crispr_umi' has be more than or equal to 1. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+fi
 if [[ -n "$VIASH_META_CPUS" ]]; then
   if ! [[ "$VIASH_META_CPUS" =~ ^[-+]?[0-9]+$ ]]; then
     ViashError 'cpus' has to be an integer. Use "--help" to get more information on the parameters.
@@ -1102,7 +1135,7 @@ fi
 
 # check whether value is belongs to a set of choices
 if [ ! -z "$VIASH_PAR_CHEMISTRY" ]; then
-  VIASH_PAR_CHEMISTRY_CHOICES=("auto:threeprime:fiveprime:SC3Pv1:SC3Pv2:SC3Pv3:SC3Pv4:SC3Pv3LT:SC3Pv3HT:SC5P-PE:SC5P-R2:SC-FB:ARC-v1")
+  VIASH_PAR_CHEMISTRY_CHOICES=("auto:threeprime:fiveprime:SC3Pv1:SC3Pv2:SC3Pv3:SC3Pv4:SC3Pv3LT:SC3Pv3HT:SC5P-PE-v3:SC5P-PE:SC5P-R2:SC-FB:ARC-v1")
   IFS=':'
   set -f
   if ! [[ ":${VIASH_PAR_CHEMISTRY_CHOICES[*]}:" =~ ":$VIASH_PAR_CHEMISTRY:" ]]; then
@@ -1216,6 +1249,7 @@ $( if [ ! -z ${VIASH_PAR_R1_LENGTH+x} ]; then echo "${VIASH_PAR_R1_LENGTH}" | se
 $( if [ ! -z ${VIASH_PAR_R2_LENGTH+x} ]; then echo "${VIASH_PAR_R2_LENGTH}" | sed "s#'#'\"'\"'#g;s#.*#par_r2_length='&'#" ; else echo "# par_r2_length="; fi )
 $( if [ ! -z ${VIASH_PAR_LANES+x} ]; then echo "${VIASH_PAR_LANES}" | sed "s#'#'\"'\"'#g;s#.*#par_lanes='&'#" ; else echo "# par_lanes="; fi )
 $( if [ ! -z ${VIASH_PAR_LIBRARY_COMPATIBILITY_CHECK+x} ]; then echo "${VIASH_PAR_LIBRARY_COMPATIBILITY_CHECK}" | sed "s#'#'\"'\"'#g;s#.*#par_library_compatibility_check='&'#" ; else echo "# par_library_compatibility_check="; fi )
+$( if [ ! -z ${VIASH_PAR_MIN_CRISPR_UMI+x} ]; then echo "${VIASH_PAR_MIN_CRISPR_UMI}" | sed "s#'#'\"'\"'#g;s#.*#par_min_crispr_umi='&'#" ; else echo "# par_min_crispr_umi="; fi )
 $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "${VIASH_META_FUNCTIONALITY_NAME}" | sed "s#'#'\"'\"'#g;s#.*#meta_functionality_name='&'#" ; else echo "# meta_functionality_name="; fi )
 $( if [ ! -z ${VIASH_META_RESOURCES_DIR+x} ]; then echo "${VIASH_META_RESOURCES_DIR}" | sed "s#'#'\"'\"'#g;s#.*#meta_resources_dir='&'#" ; else echo "# meta_resources_dir="; fi )
 $( if [ ! -z ${VIASH_META_EXECUTABLE+x} ]; then echo "${VIASH_META_EXECUTABLE}" | sed "s#'#'\"'\"'#g;s#.*#meta_executable='&'#" ; else echo "# meta_executable="; fi )
diff --git a/target/docker/mapping/cellranger_multi/cellranger_multi b/target/docker/mapping/cellranger_multi/cellranger_multi
--- a/target/docker/mapping/cellranger_multi/cellranger_multi
+++ b/target/docker/mapping/cellranger_multi/cellranger_multi
@@ -367,6 +367,17 @@ function ViashHelp {
   echo "        metrics are computed"
   echo "        and therefore, limiting the length of Read 2 may affect Q30 scores."
   echo ""
+  echo "    --min_crispr_umi"
+  echo "        type: integer"
+  echo "        min: 1"
+  echo "        Set the minimum number of CRISPR guide RNA UMIs required for protospacer"
+  echo "        detection."
+  echo "        If a lower or higher sensitivity is desired for detection, this value"
+  echo "        can be customized"
+  echo "        according to specific experimental needs. Applicable only to datasets"
+  echo "        that include a"
+  echo "        CRISPR Guide Capture library."
+  echo ""
   echo "Gene expression arguments:"
   echo "    Arguments relevant to the analysis of gene expression data."
   echo ""
@@ -422,8 +433,9 @@ function ViashHelp {
   echo "        type: string"
   echo "        default: auto"
   echo "        choices: [ auto, threeprime, fiveprime, SC3Pv1, SC3Pv2, SC3Pv3, SC3Pv4,"
-  echo "SC3Pv3LT, SC3Pv3HT, SC5P-PE, SC5P-R2, SC-FB, SC5P-R2-v3, SC5PHT, MFRP, MFRP-R1,"
-  echo "MFRP-RNA, MFRP-Ab, SFRP, MFRP-Ab-R2pos50, MFRP-RNA-R1, MFRP-Ab-R1, ARC-v1 ]"
+  echo "SC3Pv3LT, SC3Pv3HT, SC5P-PE, SC5P-R2, SC-FB, SC5P-R2-v3, SCP5-PE-v3, SC5PHT,"
+  echo "MFRP, MFRP-R1, MFRP-RNA, MFRP-Ab, SFRP, MFRP-Ab-R2pos50, MFRP-RNA-R1,"
+  echo "MFRP-Ab-R1, ARC-v1 ]"
   echo "        Assay configuration. Either specify a single value which will be applied"
   echo "        to all libraries,"
   echo "        or a number of values that is equal to the number of libararies. The"
@@ -438,6 +450,7 @@ function ViashHelp {
   echo "          - SC5P-PE: Paired-end Single Cell 5'"
   echo "          - SC5P-R2: R2-only Single Cell 5'"
   echo "          - SC5P-R2-v3: R2-only Single Cell 5' v3"
+  echo "          - SCP5-PE-v3: Single Cell 5' paired-end v3 (GEM-X)"
   echo "          - SC5PHT : Single Cell 5' v2 HT"
   echo "          - SFRP: Fixed RNA Profiling (Singleplex)"
   echo "          - MFRP: Fixed RNA Profiling (Multiplex, Probe Barcode on R2)"
@@ -842,9 +855,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Angela Oliveira Pisco, Robrecht Cannoodt, Dries De Maeyer"
 LABEL org.opencontainers.image.description="Companion container for running component mapping cellranger_multi"
-LABEL org.opencontainers.image.created="2024-06-13T02:41:33Z"
+LABEL org.opencontainers.image.created="2024-06-14T02:41:55Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="6b7dceade42a9fd30076c90b3cd0af10b46da8e8"
+LABEL org.opencontainers.image.revision="00610b1434fd34a8205c9ba31204a3a9584015f3"
 LABEL org.opencontainers.image.version="integration_build"
 
 VIASHDOCKER
@@ -1365,6 +1378,17 @@ while [[ $# -gt 0 ]]; do
         --feature_r2_length=*)
             [ -n "$VIASH_PAR_FEATURE_R2_LENGTH" ] && ViashError Bad arguments for option \'--feature_r2_length=*\': \'$VIASH_PAR_FEATURE_R2_LENGTH\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
             VIASH_PAR_FEATURE_R2_LENGTH=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --min_crispr_umi)
+            [ -n "$VIASH_PAR_MIN_CRISPR_UMI" ] && ViashError Bad arguments for option \'--min_crispr_umi\': \'$VIASH_PAR_MIN_CRISPR_UMI\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_MIN_CRISPR_UMI="$2"
+            [ $# -lt 2 ] && ViashError Not enough arguments passed to --min_crispr_umi. Use "--help" to get more information on the parameters. && exit 1
+            shift 2
+            ;;
+        --min_crispr_umi=*)
+            [ -n "$VIASH_PAR_MIN_CRISPR_UMI" ] && ViashError Bad arguments for option \'--min_crispr_umi=*\': \'$VIASH_PAR_MIN_CRISPR_UMI\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_MIN_CRISPR_UMI=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --gex_reference)
@@ -2022,6 +2046,16 @@ if [[ -n "$VIASH_PAR_FEATURE_R2_LENGTH" ]]; then
     exit 1
   fi
 fi
+if [[ -n "$VIASH_PAR_MIN_CRISPR_UMI" ]]; then
+  if ! [[ "$VIASH_PAR_MIN_CRISPR_UMI" =~ ^[-+]?[0-9]+$ ]]; then
+    ViashError '--min_crispr_umi' has to be an integer. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+  if [[ $VIASH_PAR_MIN_CRISPR_UMI -lt 1 ]]; then
+    ViashError '--min_crispr_umi' has be more than or equal to 1. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+fi
 if [[ -n "$VIASH_PAR_GEX_SECONDARY_ANALYSIS" ]]; then
   if ! [[ "$VIASH_PAR_GEX_SECONDARY_ANALYSIS" =~ ^(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)$ ]]; then
     ViashError '--gex_secondary_analysis' has to be a boolean. Use "--help" to get more information on the parameters.
@@ -2173,7 +2207,7 @@ if [ ! -z "$VIASH_PAR_LIBRARY_TYPE" ]; then
 fi
 
 if [ ! -z "$VIASH_PAR_GEX_CHEMISTRY" ]; then
-  VIASH_PAR_GEX_CHEMISTRY_CHOICES=("auto:threeprime:fiveprime:SC3Pv1:SC3Pv2:SC3Pv3:SC3Pv4:SC3Pv3LT:SC3Pv3HT:SC5P-PE:SC5P-R2:SC-FB:SC5P-R2-v3:SC5PHT:MFRP:MFRP-R1:MFRP-RNA:MFRP-Ab:SFRP:MFRP-Ab-R2pos50:MFRP-RNA-R1:MFRP-Ab-R1:ARC-v1")
+  VIASH_PAR_GEX_CHEMISTRY_CHOICES=("auto:threeprime:fiveprime:SC3Pv1:SC3Pv2:SC3Pv3:SC3Pv4:SC3Pv3LT:SC3Pv3HT:SC5P-PE:SC5P-R2:SC-FB:SC5P-R2-v3:SCP5-PE-v3:SC5PHT:MFRP:MFRP-R1:MFRP-RNA:MFRP-Ab:SFRP:MFRP-Ab-R2pos50:MFRP-RNA-R1:MFRP-Ab-R1:ARC-v1")
   IFS=':'
   set -f
   if ! [[ ":${VIASH_PAR_GEX_CHEMISTRY_CHOICES[*]}:" =~ ":$VIASH_PAR_GEX_CHEMISTRY:" ]]; then
@@ -2430,6 +2464,7 @@ par = {
   'feature_reference': $( if [ ! -z ${VIASH_PAR_FEATURE_REFERENCE+x} ]; then echo "r'${VIASH_PAR_FEATURE_REFERENCE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'feature_r1_length': $( if [ ! -z ${VIASH_PAR_FEATURE_R1_LENGTH+x} ]; then echo "int(r'${VIASH_PAR_FEATURE_R1_LENGTH//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'feature_r2_length': $( if [ ! -z ${VIASH_PAR_FEATURE_R2_LENGTH+x} ]; then echo "int(r'${VIASH_PAR_FEATURE_R2_LENGTH//\'/\'\"\'\"r\'}')"; else echo None; fi ),
+  'min_crispr_umi': $( if [ ! -z ${VIASH_PAR_MIN_CRISPR_UMI+x} ]; then echo "int(r'${VIASH_PAR_MIN_CRISPR_UMI//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'gex_reference': $( if [ ! -z ${VIASH_PAR_GEX_REFERENCE+x} ]; then echo "r'${VIASH_PAR_GEX_REFERENCE//\'/\'\"\'\"r\'}'"; else echo None; fi ),
   'gex_secondary_analysis': $( if [ ! -z ${VIASH_PAR_GEX_SECONDARY_ANALYSIS+x} ]; then echo "r'${VIASH_PAR_GEX_SECONDARY_ANALYSIS//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
   'gex_generate_bam': $( if [ ! -z ${VIASH_PAR_GEX_GENERATE_BAM+x} ]; then echo "r'${VIASH_PAR_GEX_GENERATE_BAM//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi ),
@@ -2538,6 +2573,7 @@ FEATURE_CONFIG_KEYS = {
     "feature_reference": "reference",
     "feature_r1_length": "r1-length",
     "feature_r2_length": "r2-length",
+    "min_crispr_umi": "min-crispr-umi",
 }
 
 VDJ_CONFIG_KEYS = {"vdj_reference": "reference",
@@ -2704,6 +2740,9 @@ def handle_integers_not_set(par: dict[str, Any], viash_config: Path | str) -> st
             continue
         par_value, is_multiple = par[arg_name], arg["multiple"]
         assert is_multiple in (True, False)
+
+        if not is_multiple:
+            continue
 
         def replace_notset_values(integer_value: int) -> int | None:
             return None if integer_value == -1 else integer_value
