deploy: 762575a8f5e52add5ed46f45d4895000873acd8e

diff --git a/target/docker/filter/filter_with_scrublet/filter_with_scrublet b/target/docker/filter/filter_with_scrublet/filter_with_scrublet
--- a/target/docker/filter/filter_with_scrublet/filter_with_scrublet
+++ b/target/docker/filter/filter_with_scrublet/filter_with_scrublet
@@ -248,6 +248,12 @@ function ViashHelp {
   echo "        type: string"
   echo "        default: euclidean"
   echo "        The distance metric used for computing similarities."
+  echo ""
+  echo "    --allow_automatic_threshold_detection_fail"
+  echo "        type: boolean_true"
+  echo "        When scrublet fails to automatically determine the double score"
+  echo "        threshold,"
+  echo "        allow the component to continue and set the output columns to NA."
 }
 
 ######## Helper functions for setting up Docker images for viash ########
@@ -472,9 +478,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries De Maeyer, Robrecht Cannoodt"
 LABEL org.opencontainers.image.description="Companion container for running component filter filter_with_scrublet"
-LABEL org.opencontainers.image.created="2023-04-24T07:02:47Z"
+LABEL org.opencontainers.image.created="2023-04-24T10:46:25Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="90e49ca27a56eb98517715ddcea94834a511ea51"
+LABEL org.opencontainers.image.revision="762575a8f5e52add5ed46f45d4895000873acd8e"
 LABEL org.opencontainers.image.version="main_build"
 VIASHDOCKER
 }
@@ -753,6 +759,11 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_DISTANCE_METRIC=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --allow_automatic_threshold_detection_fail)
+            [ -n "$VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL" ] && ViashError Bad arguments for option \'--allow_automatic_threshold_detection_fail\': \'$VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL\' \& \'$2\' - you should provide exactly one argument for this option. && exit 1
+            VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL=true
+            shift 1
+            ;;
         ---setup)
             VIASH_MODE='docker_setup'
             VIASH_DOCKER_SETUP_STRATEGY="$2"
@@ -924,6 +935,9 @@ fi
 if [ -z ${VIASH_PAR_DISTANCE_METRIC+x} ]; then
   VIASH_PAR_DISTANCE_METRIC="euclidean"
 fi
+if [ -z ${VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL+x} ]; then
+  VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL="false"
+fi
 
 # check whether required files exist
 if [ ! -z "$VIASH_PAR_INPUT" ] && [ ! -e "$VIASH_PAR_INPUT" ]; then
@@ -959,6 +973,12 @@ fi
 if [[ -n "$VIASH_PAR_NUM_PCA_COMPONENTS" ]]; then
   if ! [[ "$VIASH_PAR_NUM_PCA_COMPONENTS" =~ ^[-+]?[0-9]+$ ]]; then
     ViashError '--num_pca_components' has to be an integer. Use "--help" to get more information on the parameters.
+    exit 1
+  fi
+fi
+if [[ -n "$VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL" ]]; then
+  if ! [[ "$VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL" =~ ^(true|True|TRUE|false|False|FALSE|yes|Yes|YES|no|No|NO)$ ]]; then
+    ViashError '--allow_automatic_threshold_detection_fail' has to be a boolean_true. Use "--help" to get more information on the parameters.
     exit 1
   fi
 fi
@@ -1093,6 +1113,7 @@ import mudata as mu
 import numpy as np
 import logging
 from sys import stdout
+import pandas as pd 
 
 logger = logging.getLogger()
 logger.setLevel(logging.INFO)
@@ -1115,7 +1136,8 @@ par = {
   'min_cells': $( if [ ! -z ${VIASH_PAR_MIN_CELLS+x} ]; then echo "int(r'${VIASH_PAR_MIN_CELLS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'min_gene_variablity_percent': $( if [ ! -z ${VIASH_PAR_MIN_GENE_VARIABLITY_PERCENT+x} ]; then echo "float(r'${VIASH_PAR_MIN_GENE_VARIABLITY_PERCENT//\'/\'\"\'\"r\'}')"; else echo None; fi ),
   'num_pca_components': $( if [ ! -z ${VIASH_PAR_NUM_PCA_COMPONENTS+x} ]; then echo "int(r'${VIASH_PAR_NUM_PCA_COMPONENTS//\'/\'\"\'\"r\'}')"; else echo None; fi ),
-  'distance_metric': $( if [ ! -z ${VIASH_PAR_DISTANCE_METRIC+x} ]; then echo "r'${VIASH_PAR_DISTANCE_METRIC//\'/\'\"\'\"r\'}'"; else echo None; fi )
+  'distance_metric': $( if [ ! -z ${VIASH_PAR_DISTANCE_METRIC+x} ]; then echo "r'${VIASH_PAR_DISTANCE_METRIC//\'/\'\"\'\"r\'}'"; else echo None; fi ),
+  'allow_automatic_threshold_detection_fail': $( if [ ! -z ${VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL+x} ]; then echo "r'${VIASH_PAR_ALLOW_AUTOMATIC_THRESHOLD_DETECTION_FAIL//\'/\'\"\'\"r\'}'.lower() == 'true'"; else echo None; fi )
 }
 meta = {
   'functionality_name': $( if [ ! -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then echo "r'${VIASH_META_FUNCTIONALITY_NAME//\'/\'\"\'\"r\'}'"; else echo None; fi ),
@@ -1152,16 +1174,33 @@ doublet_scores, predicted_doublets = scrub.scrub_doublets(
     distance_metric=par["distance_metric"],
     use_approx_neighbors=False
 )
-keep_cells = np.invert(predicted_doublets)
+
+try:
+    keep_cells = np.invert(predicted_doublets)
+except TypeError:
+    if par['allow_automatic_threshold_detection_fail']:
+        # Scrublet might not throw an error and return None if it fails to detect doublets...
+        logger.info("\\tScrublet could not automatically detect the doublet score threshold. Setting output columns to NA.")
+        keep_cells = np.nan
+        doublet_scores = np.nan
+    else:
+        raise RuntimeError("Scrublet could not automatically detect the doublet score threshold. "
+                           "--allow_automatic_threshold_detection_fail can be used to ignore this failure "
+                           "and set the corresponding output columns to NA.")
 
 logger.info("\\tStoring output into .obs")
 if par["obs_name_doublet_score"] is not None:
     data.obs[par["obs_name_doublet_score"]] = doublet_scores
+    data.obs[par["obs_name_doublet_score"]] = data.obs[par["obs_name_doublet_score"]].astype("float64")
 if par["obs_name_filter"] is not None:
     data.obs[par["obs_name_filter"]] = keep_cells
+    data.obs[par["obs_name_filter"]] = data.obs[par["obs_name_filter"]].astype(pd.BooleanDtype())
 
 if par["do_subset"]:
-    mdata.mod[mod] = data[keep_cells, :]
+    if pd.api.types.is_scalar(keep_cells) and pd.isna(keep_cells):
+        logger.warning("Not subsetting beacuse doublets were not predicted")
+    else: 
+        mdata.mod[mod] = data[keep_cells, :]
 
 logger.info("Writing h5mu to %s", par["output"])
 mdata.write_h5mu(par["output"], compression=par["output_compression"])
