deploy: 046363b2986affd608f6e48a6f5197ae42ad6710

diff --git a/target/docker/cluster/leiden/leiden b/target/docker/cluster/leiden/leiden
--- a/target/docker/cluster/leiden/leiden
+++ b/target/docker/cluster/leiden/leiden
@@ -208,7 +208,7 @@ function ViashHelp {
   echo "        resolutions."
   echo ""
   echo "    --resolution"
-  echo "        type: double, multiple values allowed"
+  echo "        type: double, required parameter, multiple values allowed"
   echo "        default: 1.0"
   echo "        A parameter value controlling the coarseness of the clustering. Higher"
   echo "        values lead to more clusters."
@@ -445,9 +445,9 @@ RUN pip install --upgrade pip && \
 
 LABEL org.opencontainers.image.authors="Dries De Maeyer"
 LABEL org.opencontainers.image.description="Companion container for running component cluster leiden"
-LABEL org.opencontainers.image.created="2023-10-06T12:37:53Z"
+LABEL org.opencontainers.image.created="2023-10-09T08:43:34Z"
 LABEL org.opencontainers.image.source="https://github.com/openpipelines-bio/openpipeline"
-LABEL org.opencontainers.image.revision="dea329e1a96845cf3feb2668fe6cca8bd2fe92dc"
+LABEL org.opencontainers.image.revision="046363b2986affd608f6e48a6f5197ae42ad6710"
 LABEL org.opencontainers.image.version="main_build"
 
 VIASHDOCKER
@@ -823,6 +823,10 @@ if [ -z ${VIASH_PAR_OUTPUT+x} ]; then
   ViashError '--output' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z ${VIASH_PAR_RESOLUTION+x} ]; then
+  ViashError '--resolution' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z ${VIASH_META_FUNCTIONALITY_NAME+x} ]; then
   ViashError 'functionality_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -853,9 +857,6 @@ if [ -z ${VIASH_PAR_OBSP_CONNECTIVITIES+x} ]; then
 fi
 if [ -z ${VIASH_PAR_OBSM_NAME+x} ]; then
   VIASH_PAR_OBSM_NAME="leiden"
-fi
-if [ -z ${VIASH_PAR_RESOLUTION+x} ]; then
-  VIASH_PAR_RESOLUTION="1.0"
 fi
 
 # check whether required files exist
