deploy: 2332ed370441876db677354df8e0dc2a0a7ce3a0

diff --git a/target/docker/mapping/bd_rhapsody_wta/bd_rhapsody_wta b/target/docker/mapping/bd_rhapsody_wta/bd_rhapsody_wta
--- a/target/docker/mapping/bd_rhapsody_wta/bd_rhapsody_wta
+++ b/target/docker/mapping/bd_rhapsody_wta/bd_rhapsody_wta
@@ -192,6 +192,280 @@ echo "        Disable Refined Putative Cell Calling - Determine putative cells u
 echo ""
 
 }
+######## Helper functions for setting up Docker images for viash ########
+
+
+# ViashDockerRemoteTagCheck: check whether a Docker image is available 
+# on a remote. Assumes `docker login` has been performed, if relevant.
+#
+# $1                  : image identifier with format `[registry/]image[:tag]`
+# exit code $?        : whether or not the image was found
+# examples:
+#   ViashDockerRemoteTagCheck python:latest
+#   echo $?                                     # returns '0'
+#   ViashDockerRemoteTagCheck sdaizudceahifu
+#   echo $?                                     # returns '1'
+function ViashDockerRemoteTagCheck {
+  docker manifest inspect $1 > /dev/null 2> /dev/null
+}
+
+# ViashDockerLocalTagCheck: check whether a Docker image is available locally
+#
+# $1                  : image identifier with format `[registry/]image[:tag]`
+# exit code $?        : whether or not the image was found
+# examples:
+#   docker pull python:latest
+#   ViashDockerLocalTagCheck python:latest
+#   echo $?                                     # returns '0'
+#   ViashDockerLocalTagCheck sdaizudceahifu
+#   echo $?                                     # returns '1'
+function ViashDockerLocalTagCheck {
+  [ -n "$(docker images -q $1)" ]
+}
+
+# ViashDockerPull: pull a Docker image
+#
+# $1                  : image identifier with format `[registry/]image[:tag]`
+# exit code $?        : whether or not the image was found
+# examples:
+#   ViashDockerPull python:latest
+#   echo $?                                     # returns '0'
+#   ViashDockerPull sdaizudceahifu
+#   echo $?                                     # returns '1'
+function ViashDockerPull {
+  ViashNotice "Running 'docker pull $1'"
+  docker pull $1 && return 0 || return 1
+}
+
+# ViashDockerPullElseBuild: pull a Docker image, else build it
+#
+# $1                  : image identifier with format `[registry/]image[:tag]`
+# ViashDockerBuild    : a Bash function which builds a docker image, takes image identifier as argument.
+# examples:
+#   ViashDockerPullElseBuild mynewcomponent
+function ViashDockerPullElseBuild {
+  set +e
+  ViashDockerPull $1
+  out=$?
+  set -e
+  if [ $out -ne 0 ]; then
+    ViashDockerBuild $@
+  fi
+}
+
+# ViashDockerSetup: create a Docker image, according to specified docker setup strategy
+#
+# $1                  : image identifier with format `[registry/]image[:tag]`
+# $2                  : docker setup strategy, see DockerSetupStrategy.scala
+# ViashDockerBuild    : a Bash function which builds a docker image, takes image identifier as argument.
+# examples:
+#   ViashDockerSetup mynewcomponent alwaysbuild
+function ViashDockerSetup {
+  VSHD_ID="$1"
+  VSHD_STRAT="$2"
+  if [ "$VSHD_STRAT" == "alwaysbuild" -o "$VSHD_STRAT" == "build" -o "$VSHD_STRAT" == "b" ]; then
+    ViashDockerBuild $VSHD_ID --no-cache
+  elif [ "$VSHD_STRAT" == "alwayspull" -o "$VSHD_STRAT" == "pull" -o "$VSHD_STRAT" == "p" ]; then
+    ViashDockerPull $VSHD_ID
+  elif [ "$VSHD_STRAT" == "alwayspullelsebuild" -o "$VSHD_STRAT" == "pullelsebuild" ]; then
+    ViashDockerPullElseBuild $VSHD_ID --no-cache
+  elif [ "$VSHD_STRAT" == "alwayspullelsecachedbuild" -o "$VSHD_STRAT" == "pullelsecachedbuild" ]; then
+    ViashDockerPullElseBuild $VSHD_ID
+  elif [ "$VSHD_STRAT" == "alwayscachedbuild" -o "$VSHD_STRAT" == "cachedbuild" -o "$VSHD_STRAT" == "cb" ]; then
+    ViashDockerBuild $VSHD_ID
+  elif [[ "$VSHD_STRAT" =~ ^ifneedbe ]]; then
+    set +e
+    ViashDockerLocalTagCheck $VSHD_ID
+    outCheck=$?
+    set -e
+    if [ $outCheck -eq 0 ]; then
+      ViashInfo "Image $VSHD_ID already exists"
+    elif [ "$VSHD_STRAT" == "ifneedbebuild" ]; then
+      ViashDockerBuild $VSHD_ID --no-cache
+    elif [ "$VSHD_STRAT" == "ifneedbecachedbuild" ]; then
+      ViashDockerBuild $VSHD_ID
+    elif [ "$VSHD_STRAT" == "ifneedbepull" ]; then
+      ViashDockerPull $VSHD_ID
+    elif [ "$VSHD_STRAT" == "ifneedbepullelsebuild" ]; then
+      ViashDockerPullElseBuild $VSHD_ID --no-cache
+    elif [ "$VSHD_STRAT" == "ifneedbepullelsecachedbuild" ]; then
+      ViashDockerPullElseBuild $VSHD_ID
+    else
+      ViashError "Unrecognised Docker strategy: $VSHD_STRAT"
+      exit 1
+    fi
+  elif [ "$VSHD_STRAT" == "push" -o "$VSHD_STRAT" == "forcepush" -o "$VSHD_STRAT" == "alwayspush" ]; then
+    set +e
+    docker push $VSHD_ID
+    outPush=$?
+    set -e
+    if [ $outPush -eq 0 ]; then
+      ViashNotice "Container '$VSHD_ID' push succeeded."
+    else
+      ViashError "Container '$VSHD_ID' push errored."
+      exit 1
+    fi
+  elif [ "$VSHD_STRAT" == "pushifnotpresent" -o "$VSHD_STRAT" == "gentlepush" -o "$VSHD_STRAT" == "maybepush" ]; then
+    set +e
+    ViashDockerRemoteTagCheck $VSHD_ID
+    outCheck=$?
+    set -e
+    if [ $outCheck -eq 0 ]; then
+      ViashNotice "Container '$VSHD_ID' exists, doing nothing."
+    else
+      ViashNotice "Container '$VSHD_ID' does not yet exist."
+      set +e
+      docker push $1 > /dev/null 2> /dev/null
+      outPush=$?
+      set -e
+      if [ $outPush -eq 0 ]; then
+        ViashNotice "Container '$VSHD_ID' push succeeded."
+      else
+      ViashError "Container '$VSHD_ID' push errored."
+        exit 1
+      fi
+    fi
+  elif [ "$VSHD_STRAT" == "donothing" -o "$VSHD_STRAT" == "meh" ]; then
+    ViashNotice "Skipping setup."
+  else
+    ViashError "Unrecognised Docker strategy: $VSHD_STRAT"
+    exit 1
+  fi
+}
+
+
+######## End of helper functions for setting up Docker images for viash ########
+
+# ViashDockerFile: print the dockerfile to stdout
+# return : dockerfile required to run this component
+# examples:
+#   ViashDockerFile
+function ViashDockerfile {
+  cat << 'VIASHDOCKER'
+FROM bdgenomics/rhapsody:1.9.1
+
+RUN apt-get update && \
+  apt-get install -y cwltool && \
+  rm -rf /var/lib/apt/lists/*
+
+VIASHDOCKER
+}
+
+# ViashDockerBuild: build a docker container
+# $1              : image identifier with format `[registry/]image[:tag]`
+# exit code $?    : whether or not the image was built
+function ViashDockerBuild {
+
+  # create temporary directory to store dockerfile & optional resources in
+  tmpdir=$(mktemp -d "$VIASH_TEMP/viashsetupdocker-bd_rhapsody_wta-XXXXXX")
+  function clean_up {
+    rm -rf "$tmpdir"
+  }
+  trap clean_up EXIT
+
+  # store dockerfile and resources
+  ViashDockerfile > $tmpdir/Dockerfile
+  cp -r $VIASH_RESOURCES_DIR/* $tmpdir
+
+  # Build the container
+  ViashNotice "Running 'docker build -t $@ $tmpdir'"
+  set +e
+  if [ $VIASH_VERBOSITY -ge 6 ]; then
+    docker build -t $@ $tmpdir
+  else
+    docker build -t $@ $tmpdir &> $tmpdir/docker_build.log
+  fi
+  out=$?
+  set -e
+  if [ ! $out -eq 0 ]; then
+    ViashError "Error occurred while building the container $@."
+    if [ ! $VIASH_VERBOSITY -ge 6 ]; then
+      ViashError "Transcript: --------------------------------"
+      cat "$tmpdir/docker_build.log"
+      ViashError "End of transcript --------------------------"
+    fi
+    exit 1
+  fi
+}
+# ViashAbsolutePath: generate absolute path from relative path
+# borrowed from https://stackoverflow.com/a/21951256
+# $1     : relative filename
+# return : absolute path
+# examples:
+#   ViashAbsolutePath some_file.txt   # returns /path/to/some_file.txt
+#   ViashAbsolutePath /foo/bar/..     # returns /foo
+function ViashAbsolutePath {
+  local thePath
+  if [[ ! "$1" =~ ^/ ]]; then
+    thePath="$PWD/$1"
+  else
+    thePath="$1"
+  fi
+  echo "$thePath" | (
+    IFS=/
+    read -a parr
+    declare -a outp
+    for i in "${parr[@]}"; do
+      case "$i" in
+      ''|.) continue ;;
+      ..)
+        len=${#outp[@]}
+        if ((len==0)); then
+          continue
+        else
+          unset outp[$((len-1))]
+        fi
+        ;;
+      *)
+        len=${#outp[@]}
+        outp[$len]="$i"
+      ;;
+      esac
+    done
+    echo /"${outp[*]}"
+  )
+}
+# ViashAutodetectMount: auto configuring docker mounts from parameters
+# $1                  : The parameter value
+# returns             : New parameter
+# $VIASH_EXTRA_MOUNTS : Added another parameter to be passed to docker
+# examples:
+#   ViashAutodetectMount /path/to/bar      # returns '/viash_automount/path/to/bar'
+#   ViashAutodetectMountArg /path/to/bar   # returns '-v /path/to:/viash_automount/path/to'
+function ViashAutodetectMount {
+  abs_path=$(ViashAbsolutePath "$1")
+  if [ -d "$abs_path" ]; then
+    mount_source="$abs_path"
+    base_name=""
+  else
+    mount_source=`dirname "$abs_path"`
+    base_name=`basename "$abs_path"`
+  fi
+  mount_target="/viash_automount$mount_source"
+  echo "$mount_target/$base_name"
+}
+function ViashAutodetectMountArg {
+  abs_path=$(ViashAbsolutePath "$1")
+  if [ -d "$abs_path" ]; then
+    mount_source="$abs_path"
+    base_name=""
+  else
+    mount_source=`dirname "$abs_path"`
+    base_name=`basename "$abs_path"`
+  fi
+  mount_target="/viash_automount$mount_source"
+  echo "-v \"$mount_source:$mount_target\""
+}
+# ViashExtractFlags: Retain leading flag
+# $1     : string with a possible leading flag
+# return : leading flag
+# examples:
+#   ViashExtractFlags --foo=bar  # returns --foo
+function ViashExtractFlags {
+  echo $1 | sed 's/=.*//'
+}
+# initialise variables
+VIASH_EXTRA_MOUNTS=''
 
 # initialise array
 VIASH_POSITIONAL_ARGS=''
@@ -306,6 +580,31 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_DISABLE_PUTATIVE_CALLING=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        ---setup)
+            ViashDockerSetup 'openpipeline/mapping_bd_rhapsody_wta:main_build' "$2"
+            exit 0
+            ;;
+        ---setup=*)
+            ViashDockerSetup 'openpipeline/mapping_bd_rhapsody_wta:main_build' "$(ViashRemoveFlags "$1")"
+            exit 0
+            ;;
+        ---dockerfile)
+            ViashDockerfile
+            exit 0
+            ;;
+        ---v|---volume)
+            VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS -v "$2""
+            shift 2
+            ;;
+        ---volume=*)
+            VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS -v $(ViashRemoveFlags "$2")"
+            shift 1
+            ;;
+        ---debug)
+            ViashNotice "+ docker run --entrypoint=bash -i --rm -v "$(pwd)":/pwd --workdir /pwd -t openpipeline/mapping_bd_rhapsody_wta:main_build"
+            docker run --entrypoint=bash -i --rm -v "$(pwd)":/pwd --workdir /pwd -t openpipeline/mapping_bd_rhapsody_wta:main_build
+            exit 0
+            ;;
         *)  # positional arg or unknown option
             # since the positional args will be eval'd, can we always quote, instead of using ViashQuote
             VIASH_POSITIONAL_ARGS="$VIASH_POSITIONAL_ARGS '$1'"
@@ -338,8 +637,54 @@ if [ -z "$VIASH_PAR_OUTPUT" ]; then
 fi
 
 
+ViashDockerSetup 'openpipeline/mapping_bd_rhapsody_wta:main_build' ifneedbepullelsecachedbuild
 
-cat << VIASHEOF | bash
+# detect volumes from file arguments
+if [ ! -z "$VIASH_PAR_INPUT" ]; then
+  IFS=":"
+  for var in $VIASH_PAR_INPUT; do
+    unset IFS
+    VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$var")"
+    if [ -z "$VIASH_TEST_INPUT" ]; then
+      VIASH_TEST_INPUT="$(ViashAutodetectMount "$var")"
+    else
+      VIASH_TEST_INPUT="$VIASH_TEST_INPUT:""$(ViashAutodetectMount "$var")"
+    fi
+  done
+  VIASH_PAR_INPUT="$VIASH_TEST_INPUT"
+fi
+if [ ! -z "$VIASH_PAR_REFERENCE_GENOME" ]; then
+  VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_REFERENCE_GENOME")"
+  VIASH_PAR_REFERENCE_GENOME=$(ViashAutodetectMount "$VIASH_PAR_REFERENCE_GENOME")
+fi
+if [ ! -z "$VIASH_PAR_TRANSCRIPTOME_ANNOTATION" ]; then
+  VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_TRANSCRIPTOME_ANNOTATION")"
+  VIASH_PAR_TRANSCRIPTOME_ANNOTATION=$(ViashAutodetectMount "$VIASH_PAR_TRANSCRIPTOME_ANNOTATION")
+fi
+if [ ! -z "$VIASH_PAR_OUTPUT" ]; then
+  VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT")"
+  VIASH_PAR_OUTPUT=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT")
+fi
+
+# Always mount the resource directory
+VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_RESOURCES_DIR")"
+VIASH_RESOURCES_DIR=$(ViashAutodetectMount "$VIASH_RESOURCES_DIR")
+
+# Always mount the VIASH_TEMP directory
+VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_TEMP")"
+VIASH_TEMP=$(ViashAutodetectMount "$VIASH_TEMP")
+
+# change file ownership
+function viash_perform_chown {
+  
+  if [ ! -z "$VIASH_PAR_OUTPUT" ]; then
+    eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openpipeline/mapping_bd_rhapsody_wta:main_build "$(id -u):$(id -g)" -R "$VIASH_PAR_OUTPUT"
+  fi
+}
+trap viash_perform_chown EXIT
+
+
+cat << VIASHEOF | eval docker run --entrypoint=bash -i --rm $VIASH_EXTRA_MOUNTS openpipeline/mapping_bd_rhapsody_wta:main_build
 set -e
 tempscript=\$(mktemp "$VIASH_TEMP/viash-run-bd_rhapsody_wta-XXXXXX")
 function clean_up {
